/* ============================================================================
   HUD — the camcorder's burned-in on-screen display.

   This is not a game UI. It is characters generated by the camera's character
   generator and recorded onto the tape as part of the picture, which is why
   postfx composites it *inside* the tape stage: the OSD gets the same chroma
   smear, the same tracking tear and the same noise as everything else. Anything
   here that looks crisp is wrong.

   Consumer camcorder OSD conventions being followed:
   * white characters with a hard black drop-shadow one pixel down-right, which
     is how they stayed legible over any scene
   * REC with a dot that blinks about once a second
   * a battery gauge that never quite tells you anything
   * the date/time burn-in bottom-right, in the AUG 17 1987 / 10:42:13 PM form
   * everything nailed to the safe-area inset, not the frame edge
   ========================================================================== */
VB.def('hud', function (VB, THREE) {
  const S = VB.S;
  let c, g, tx;
  let blink = 0, dot = true;
  let trackingUntil = -1, lastBurst = 0;

  /* The tape's own clock. Starts at a plausible "already been recording a
     while" offset so the counter never reads as a session that began when the
     player pressed play. */
  const T0 = 42 * 60 + 17;
  const START = { mo: 7, d: 17, h: 22, mi: 42, s: 13 };   // AUG 17 1987, 10:42 PM
  const MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
  const p2 = n => (n < 10 ? '0' : '') + n;

  /* A blocky character look. The condensed transform is doing real work: it is
     what separates a camcorder character generator from a web font. */
  function osd(text, x, y, size, align) {
    g.save();
    g.font = 'bold ' + size + 'px "Courier New",Courier,monospace';
    g.textAlign = align || 'left';
    g.textBaseline = 'alphabetic';
    g.translate(x, y);
    g.scale(0.86, 1.12);                 // tall and narrow, like the real thing
    g.fillStyle = 'rgba(0,0,0,0.85)';    // the drop shadow that keeps it legible
    g.fillText(text, 2, 2);
    g.fillStyle = '#fdfdf6';
    g.fillText(text, 0, 0);
    g.restore();
  }

  return {
    init() {
      c = document.createElement('canvas');
      c.width = 640; c.height = 480;
      g = c.getContext('2d');
      tx = new THREE.CanvasTexture(c);
      tx.minFilter = THREE.LinearFilter;
      tx.magFilter = THREE.LinearFilter;
      tx.generateMipmaps = false;
      /* Leave flipY at its default. postfx samples tHud with the frame's own
         uv, where v=1 is the top of the picture; CanvasTexture's default flip
         already maps the canvas's top row there. Forcing flipY=false inverts
         the whole OSD. */
      VB.hud = { texture: tx, w: c.width, h: c.height };
      VB.on('glitch:burst', () => {
        /* the character generator loses sync when the signal does */
        if (Math.random() < 0.55) trackingUntil = S.t + 0.8 + Math.random() * 1.6;
      });
    },

    lateUpdate(dt) {
      g.clearRect(0, 0, c.width, c.height);

      blink += dt;
      if (blink > 0.5) { blink = 0; dot = !dot; }

      const IX = 46, IY = 40;            // safe-area inset

      /* ---- REC, top left ---- */
      if (dot) {
        g.fillStyle = 'rgba(0,0,0,0.85)';
        g.beginPath(); g.arc(IX + 2, IY - 7, 9, 0, 7); g.fill();
        g.fillStyle = '#fdfdf6';
        g.beginPath(); g.arc(IX, IY - 9, 9, 0, 7); g.fill();
      }
      osd('REC', IX + 20, IY, 25);

      /* ---- tape counter, top right ---- */
      const tt = T0 + S.t;
      osd(p2(Math.floor(tt / 3600)) + ':' + p2(Math.floor(tt / 60) % 60) + ':' + p2(Math.floor(tt) % 60),
        c.width - IX, IY, 25, 'right');

      /* ---- battery, under the counter. Drains over the run. ---- */
      const bx = c.width - IX - 62, by = IY + 20;
      const bat = VB.clamp(1 - S.t / 4200, 0.06, 1);
      g.fillStyle = 'rgba(0,0,0,0.85)'; g.fillRect(bx + 2, by + 2, 56, 20);
      g.strokeStyle = '#fdfdf6'; g.lineWidth = 2.5;
      g.strokeRect(bx, by, 54, 18);
      g.fillStyle = '#fdfdf6'; g.fillRect(bx + 54, by + 5, 5, 8);
      /* the last bar flashes, because it always did */
      if (bat > 0.18 || dot) g.fillRect(bx + 4, by + 4, Math.max(3, 46 * bat), 10);

      /* ---- date/time burn-in, bottom right ---- */
      let sec = START.s + S.t, mi = START.mi + Math.floor(sec / 60), h = START.h;
      sec = Math.floor(sec % 60);
      h += Math.floor(mi / 60); mi = mi % 60;
      let d = START.d + Math.floor(h / 24); h = h % 24;
      const ampm = h >= 12 ? 'PM' : 'AM';
      const h12 = h % 12 === 0 ? 12 : h % 12;
      osd(MONTHS[START.mo] + ' ' + p2(d) + ' 1987', c.width - IX, c.height - IY - 30, 24, 'right');
      osd(p2(h12) + ':' + p2(mi) + ':' + p2(sec) + ' ' + ampm, c.width - IX, c.height - IY, 24, 'right');

      /* ---- TRACKING, bottom left, only while the signal is unstable ---- */
      if (S.t < trackingUntil || S.burst > 0.25) {
        osd('TRACKING', IX, c.height - IY, 24);
      }

      /* ---- SP tape speed, a detail that is only ever right or absent ---- */
      osd('SP', IX, IY + 34, 22);

      tx.needsUpdate = true;
    },
  };
}, 60);
